services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - webnet

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./BackEnd/.env
    volumes:
      - ./BackEnd:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - webnet

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./FrontEnd/.env
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - webnet

volumes:
  mongodb_data:
    driver: local
networks:
  webnet:
    driver: bridge